# Generated by Django 5.2.14 on 2026-06-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='auditor.contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clause',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='auditor.contract'),
        ),
    ]
